FROM centos
MAINTAINER Managed Kaos (info@managedkaos)
#RUN apk add --no-cache \
#    alpine-sdk \
#    autoconf \
#    automake \
#    gettext \
#    git \
#    libtool \
#    python2 \
#    rrdtool && \
#    git clone http://github.com/cherokee/webserver.git
#WORKDIR /webserver
#RUN ./autogen.sh --prefix=/usr --sysconfdir=/etc --localstatedir=/var && \
#    make && make install
WORKDIR /

EXPOSE 80
EXPOSE 443
EXPOSE 9090

#CMD ["/usr/sbin/cherokee-worker"]

